=== take-easy-soft/easy-generator/res/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Api": {
            "description": "请求实体",
            "properties": {
                "desc": {
                    "description": "请求方法注释",
                    "type": "string"
                },
                "method": {
                    "$ref": "#/definitions/ApiType",
                    "description": "请求类型"
                },
                "name": {
                    "description": "请求方法名称",
                    "type": "string"
                },
                "path": {
                    "description": "请求路径",
                    "type": "string"
                },
                "request": {
                    "description": "API 请求参数",
                    "properties": {
                        "body": {
                            "$ref": "#/definitions/Bean",
                            "description": "body参数, 会创建一个Dto实体"
                        },
                        "pathVar": {
                            "$ref": "#/definitions/Bean",
                            "description": "路径参数:/path/{param}, 会转为方法参数"
                        },
                        "queryParam": {
                            "$ref": "#/definitions/Bean",
                            "description": "query参数, 会创建一个Dto实体"
                        }
                    },
                    "type": "object"
                },
                "response": {
                    "description": "API 响应实体",
                    "properties": {
                        "body": {
                            "$ref": "#/definitions/Bean"
                        }
                    },
                    "required": [
                        "body"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "desc",
                "method",
                "name",
                "path",
                "response"
            ],
            "type": "object"
        },
        "ApiType": {
            "description": "API类型",
            "enum": [
                "DELETE",
                "GET",
                "POST",
                "PUT"
            ],
            "type": "string"
        },
        "Bean": {
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/Field"
                    },
                    {
                        "type": "boolean"
                    }
                ]
            },
            "description": "请求或响应实体",
            "properties": {
                "isList": {
                    "description": "是否支持显示为List",
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "Field": {
            "description": "请求实体参数",
            "properties": {
                "desc": {
                    "description": "参数注释",
                    "type": "string"
                },
                "isList": {
                    "description": "是否支持显示为List",
                    "type": "boolean"
                },
                "sub": {
                    "$ref": "#/definitions/Bean",
                    "description": "子实体"
                },
                "type": {
                    "$ref": "#/definitions/Type",
                    "description": "Java类型"
                },
                "valid": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/Valid"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/Valid"
                            },
                            "type": "array"
                        }
                    ],
                    "description": "参数验证,可空, 只对Dto生效"
                }
            },
            "required": [
                "desc",
                "type"
            ],
            "type": "object"
        },
        "Type": {
            "enum": [
                "Boolean",
                "Date",
                "Double",
                "Float",
                "Integer",
                "Long",
                "Object",
                "String"
            ],
            "type": "string"
        },
        "Valid": {
            "properties": {
                "max": {
                    "description": "适用于Length、Size类型",
                    "type": "number"
                },
                "message": {
                    "description": "保存信息, 非Pattern类型留空自动生成即可",
                    "type": "string"
                },
                "min": {
                    "description": "适用于Length、Size类型",
                    "type": "number"
                },
                "regexp": {
                    "description": "适用于Pattern类型",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/ValidType"
                },
                "value": {
                    "description": "适用于Max、Min类型",
                    "type": "number"
                }
            },
            "required": [
                "type"
            ],
            "type": "object"
        },
        "ValidType": {
            "enum": [
                "Length",
                "Max",
                "Min",
                "NotBlank",
                "NotEmpty",
                "NotNull",
                "Pattern",
                "Size"
            ],
            "type": "string"
        }
    },
    "properties": {
        "apis": {
            "description": "api列表",
            "items": {
                "$ref": "#/definitions/Api"
            },
            "type": "array"
        },
        "author": {
            "description": "创建者",
            "type": "string"
        },
        "definitions": {
            "description": "定义类型, 用于请求或响应复用",
            "items": {
                "$ref": "#/definitions/Bean"
            },
            "type": "array"
        },
        "desc": {
            "description": "Controller注释",
            "type": "string"
        },
        "name": {
            "description": "ClassName",
            "type": "string"
        },
        "package": {
            "description": "包名",
            "type": "string"
        },
        "path": {
            "type": "string"
        },
        "platform": {
            "description": "暂时无用",
            "type": "string"
        },
        "userType": {
            "description": "暂时无用",
            "type": "string"
        }
    },
    "required": [
        "apis",
        "author",
        "desc",
        "name",
        "package",
        "path"
    ],
    "type": "object"
}

=== take-easy-soft/easy-generator/res/test.json
{
    "$schema": "./schema.json",
    "name": "Test",
    "desc": "实例Controler",
    "package": "com.etm.test",
    "author": "etmgen",
    "path": "/test",
    "apis": [
        {
            "name": "example",
            "desc": "实例请求",
            "method": "POST",
            "path": "/example",
            "request": {
                "body": {
                    "isList": false,
                    "name": {
                        "desc": "姓名",
                        "type": "String",
                        "valid":[{ "type": "NotNull" },{ "type": "NotEmpty" }]
                    },
                    "age": {
                        "desc": "年龄",
                        "type": "Integer"
                    },
                    "content": {
                        "desc": "附加内容,内部实体",
                        "type": "Object",
                        "sub": {
                            "isList": true,
                            "content": {
                                "desc": "任意内容",
                                "type": "String"
                            },
                            "id": {
                                "desc": "id",
                                "type": "Integer"
                            }
                        }
                    },
                    "number": {
                        "desc": "编号",
                        "isList": true,
                        "type": "Integer"
                    }
                }
            },
            "response": {
                "body": {
                    "isList": false,
                    "message": {
                        "desc": "信息",
                        "type": "String"
                    }
                }
            }
        },
        {
            "name": "pathExample",
            "desc": "路径请求",
            "method": "GET",
            "path": "/path/{id}",
            "request": {
                "pathVar": {
                    "age": {
                        "desc": "年龄",
                        "type": "Integer"
                    }
                }
            },
            "response": {
                "body": {
                    "isList": true,
                    "message": {
                        "desc": "内容",
                        "type": "String"
                    }
                }
            }
        }
    ]
}
